### PR TITLE
BTCPAY: Fixes and improvements

### PR DESCRIPTION
**Pull request by dennisreimann**
The JSON response parsing was broken and I think it might still be brittle – but for now it works.

Other than that, the display and logging has been improved. Please merge as the current state is broken (BTCPay Server JSON response seems to have changed).

### CODE REVIEW

**Comment by dennisreimann** [comment]
Hey @pretyflaco, can you check if this version works for you? Thanks! :)

**Comment by arcbtc** [comment]
Dude! Sweet

**Comment by ravcodebase** [comment]
I was running into this so will test this tonight, Thanks for your efforts!

**Comment by pretyflaco** [comment]
@dennisreimann An update had messed up my Arduino IDE and I came around to fixing it only now, better late than never, right :) . Compiled your patch and flashed the device and, so far, it works like a charm! Thanks for the patch and the nicely improved display ;) !

**Pull request merged**
